<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ThuVienBaiBao.Command.Application\ThuVienBaiBao.Command.Application.csproj" />
    <ProjectReference Include="..\ThuVienBaiBao.Command.Contracts\ThuVienBaiBao.Command.Contracts.csproj" />
  </ItemGroup>

</Project>

