<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Grpc.Net.ClientFactory" Version="2.66.0" />
    <PackageReference Include="Grpc.Net.Client" Version="2.66.0" />
    <PackageReference Include="Google.Protobuf" Version="3.27.1" />
    <PackageReference Include="Grpc.Tools" Version="2.66.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\Protos\readmodel.proto" GrpcServices="Client" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ThuVienBaiBao.Command.Application\ThuVienBaiBao.Command.Application.csproj" />
    <ProjectReference Include="..\ThuVienBaiBao.Command.Persistence\ThuVienBaiBao.Command.Persistence.csproj" />
    <ProjectReference Include="..\ThuVienBaiBao.Command.Presentation\ThuVienBaiBao.Command.Presentation.csproj" />
  </ItemGroup>

</Project>

